name: Kick off a new release
description: This workflow is triggered manually to create a new release branch and optionally increment the version and build numbers.

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Select the app to release'
        required: true
        type: choice
        options:
          - Education
          - Families

jobs:
  start-release:
    # Run on macos-latest instead of ubuntu-latest because we need to run fastlane and xcodebuild
    runs-on: macos-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create release branch, with lowercase app name
        run: |
          git checkout -b test_branch

      - name: Set up GitHub CLI
        run: brew install gh
      
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GIT_PAT_TOKEN }}" | gh auth login --with-token
      
      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head test_branch \
            --title "Release: test" \
            --body "This PR was created by GitHub Actions"

