name: Kick off a new release
description: This workflow is triggered manually to create a new release branch and optionally increment the version and build numbers.

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'Select the app to release'
        required: true
        type: choice
        options:
          - Education
          - Families

jobs:
  start-release:
    # Run on macos-latest instead of ubuntu-latest because we need to run fastlane and xcodebuild
    runs-on: macos-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create release branch, with lowercase app name
        run: |
          git checkout -b test_branch

      - name: Append timestamp to README.md
        run: |
          echo "Updated at: $(date)" >> README.md

      - name: Commit change
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "test commit"

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_PAT_TOKEN }}@github.com/winseyli/simulate_sso_web.git
          git push origin test_branch

      - name: Set up GitHub CLI
        run: brew install gh
      
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GIT_PAT_TOKEN }}" | gh auth login --with-token
      
      - name: Create Pull Request
        run: |
          gh pr create \
            --base main \
            --head test_branch \
            --title "Release: test" \
            --body "This PR was created by GitHub Actions"

